[package]
name = "bevy_easings"
version = "0.4.0"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2021"
description = "Easing plugin for Bevy"
repository = "https://github.com/mockersf/bevy_extra"
homepage = "https://github.com/mockersf/bevy_extra/tree/master/bevy_easings"
documentation = "https://docs.rs/bevy_easings"
keywords = ["bevy", "animation", "easing"]
license = "MIT"
readme = "README.md"
exclude = ["examples/*.gif"]

[dependencies]
interpolation = "0.2"

[dependencies.bevy]
version = "0.5"
git = "https://github.com/bevyengine/bevy"
rev = "76ec709edee77c28a4a027ff1ab8d768be523633"
default-features = false
features = [ "render" ]

[[example]]
name = "chain"
required-features = [ "bevy/bevy_winit" ]

[[example]]
name = "sprite_color"
required-features = [ "bevy/bevy_winit" ]

[[example]]
name = "custom_component"
required-features = [ "bevy/bevy_winit" ]

[[example]]
name = "pause"
required-features = [ "bevy/bevy_winit" ]

[[example]]
name = "sprite_size"
required-features = [ "bevy/bevy_winit" ]

[[example]]
name = "transform_rotation"
required-features = [ "bevy/bevy_winit" ]

[[example]]
name = "transform_translation"
required-features = [ "bevy/bevy_winit" ]

[[example]]
name = "ui_style"
required-features = [ "bevy/bevy_winit" ]

[[example]]
name = "ui_color"
required-features = [ "bevy/bevy_winit" ]
