[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "CC0-1.0",
    "MIT-0",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = [
    { allow = ["BSD-3-Clause"], name = "instant" },
    { allow = ["BSD-3-Clause"], name = "pp-rs" },
    { allow = ["ISC"], name = "libloading" },
    { allow = ["Zlib"], name = "slotmap" },
    { allow = ["Zlib"], name = "const_panic" },
    { allow = ["Zlib"], name = "bevy_mikktspace" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
multiple-versions = "deny"
# allowed while working with git deps
# wildcards = "deny"
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
    { name = "ahash", version = "0.7" },
    { name = "bitflags", version = "1.3" },
    { name = "hashbrown", version = "0.12" },
    { name = "indexmap", version = "1.9" },
    { name = "libloading", version = "0.7" },
    { name = "num_enum", version = "0.5" },
    { name = "num_enum_derive", version = "0.5" },
    { name = "regex-automata", version = "0.1" },
    { name = "regex-syntax", version = "0.6" },
    { name = "syn", version = "1.0" },
    { name = "windows-sys", version = "0.45" },
    { name = "windows-targets", version = "0.42" },
    { name = "windows_aarch64_gnullvm", version = "0.42" },
    { name = "windows_aarch64_msvc", version = "0.42" },
    { name = "windows_i686_gnu", version = "0.42" },
    { name = "windows_i686_msvc", version = "0.42" },
    { name = "windows_x86_64_gnu", version = "0.42" },
    { name = "windows_x86_64_gnullvm", version = "0.42" },
    { name = "windows_x86_64_msvc", version = "0.42" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/bevyengine/bevy",
]